<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- automatically generated by GrammarFilter.java - do not edit here! -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Colored words</title>
<link rel="stylesheet" title="all"    type="text/css" href="stylesheet.css" />
<link rel="stylesheet" title="vbav"   type="text/css" href="vbav.css"   />
<link rel="stylesheet" title="sbajar" type="text/css" href="sbajar.css" />
<link rel="stylesheet" title="nmnu"   type="text/css" href="nmnu.css"   />
<link rel="stylesheet" title="prcj"   type="text/css" href="prcj.css"   />
<script type="text/javascript" src="script.js">
</script>
</head>
<body>
<table><tr><th width="85%" align="left">wachstube.txt </th>
<th align="left">Morphem Codes</th></tr>
<tr><td>
Wachstube 
Fernfahrer 
augenblick			 
Bahnhof 
grundlos 
Wischerblatt 
Widerspruchsgeist 
Pferdesattelknauf 
Landesamt			 
regenbogen			 
nachteile			 
regenwald			 
Hausarrest			 
zehnmal			 
beileibe			 
gesichtsausdruck	 
Altersteilzeit		 
siebenmal			 
Druckerzeugnis 
</td><td>highlight:<br />
<a href="" onclick="setActiveStyleSheet('all');    return false;">all found</a><br />
<a href="" onclick="setActiveStyleSheet('vbav');   return false;">Vb+Av</a><br />
<a href="" onclick="setActiveStyleSheet('sbajar'); return false;">Sb+Aj+Ar</a><br />
<a href="" onclick="setActiveStyleSheet('nmnu');   return false;">Nm+Nu</a><br />
<a href="" onclick="setActiveStyleSheet('prcj');   return false;">Pr+Cj+Cc+Un</a><br />
<table>
<tr><td>total</td><td align="right">19</td></tr>
<tr><td>known</td><td align="right">0</td></tr>
<tr><td>=</td><td align="right"><strong>0.0%</strong></td></tr>
</table>
</td></tr></table>
</body>
</html>


Wachstube
Fernfahrer
augenblick			
Bahnhof
grundlos
Wischerblatt
Widerspruchsgeist
Pferdesattelknauf
Landesamt			
regenbogen			
nachteile			
regenwald			
Hausarrest			
zehnmal			
beileibe			
gesichtsausdruck	
Altersteilzeit		
siebenmal			
Druckerzeugnis
GrammarServlet.endFilter
